### PR TITLE
[NSA-8704] DSi Manage - display services alphabetically

### PR DESCRIPTION
**Pull request by alexplattdfe**
Link to ticket: [NSA-8704](https://dfe-secureaccess.atlassian.net/browse/NSA-8704)

- Sorting user services and roles alphabetically 
- updated tests

### CODE REVIEW

**Comment by insacuri** [comment]
Just going to add a comment because I don't know how I feel about it.  It looks like it works so I should approve it.  But we're doing a sort in the condition part of the loop which feels... wrong?  Would a more reasonable way to do it be to sort it out ahead of time and just have the view render what it gets?  That might be heavy handed though....I'm not sure what the right answer is, and for something so small it might not even really matter 🤷

Additionally, I hate that we don't unit test views at all.  Not having a unit test for something simple like verifying that it's actually alphabetical also feels wrong.

**Review by JaredAMarsh — CHANGES_REQUESTED** [review]
Hey Alex, this will sort the names for the services alphabetically, no arguments there 👍 But I do agree with @insacuri that we should ideally do the sort in the code and then allow the view to just render it, that way we can add unit tests for the code that gets passed to the view which makes everyone's lives easier 👍 

To do that you should be able to put your sort [here](https://github.com/DFE-Digital/login.dfe.manage/blob/28d2211e3eeac060292219a64aa678cc6eef89b5/src/app/services/getUserOrganisations.js#L44) after the `.filter()` and if you want to filter the roles too, you could add a sort in for that [about here](https://github.com/DFE-Digital/login.dfe.manage/blob/28d2211e3eeac060292219a64aa678cc6eef89b5/src/app/services/getUserOrganisations.js#L50) to sort the serviceRoles as well 👍

**Review by JaredAMarsh — DISMISSED** [review]
@alexplattdfe 👋 No issues with the above, the only difference between this and my above recommendation is the sort is in a different place and I'm not going to die on a hill for that 🤣 

If you want to also sort the roles for the services that are displayed, that'd be great too for completeness 🙌

**Review by JaredAMarsh — APPROVED** [review]
Looks good to me, services were already sorted and now the roles are also sorted, all makes sense to me when reading the above 👍

**Pull request merged**
